[versions]
buildLogicJvmTarget = "21"
appJvmTarget = "17"
kotlin = "2.4.10"
agp = "9.3.1"
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"

version-code = "1"
version-name = "1.0.0"

ksp = "2.3.10"
room3 = "3.0.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-multiplatform = "org.jetbrains.compose:1.11.1"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = "dev.zacsweers.metro:1.4.2"
room3 = { id = "androidx.room3", version.ref = "room3" }

convention-kmp-library = { id = "convention-kmp-library" }
convention-kmp-compose = { id = "convention-kmp-compose" }
convention-metro = { id = "convention-metro" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.11.0"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0"
kotlinx-coroutines-swing = "org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.11.0"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0"
kotlinx-io-byteString = "org.jetbrains.kotlinx:kotlinx-io-bytestring:0.9.1"

compose-foundation = "org.jetbrains.compose.foundation:foundation:1.11.1"
compose-material3 = "org.jetbrains.compose.material3:material3:1.9.0"
compose-resources = "org.jetbrains.compose.components:components-resources:1.11.1"

androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
androidx-lifecycle-viewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.11.0"
androidx-startup = "androidx.startup:startup-runtime:1.2.0"

room3-runtime = { module = "androidx.room3:room3-runtime", version.ref = "room3" }
room3-compiler = { module = "androidx.room3:room3-compiler", version.ref = "room3" }
androidx-sqlite-bundled = "androidx.sqlite:sqlite-bundled:2.7.0"

datastore-core = "androidx.datastore:datastore:1.2.1"
datastore-preferences = "androidx.datastore:datastore-preferences:1.2.1"

metro-viewModelCompose = "dev.zacsweers.metro:metrox-viewmodel-compose:1.4.2"

ktor-core = "io.ktor:ktor-client-core:3.5.2"
ktor-okhttp = "io.ktor:ktor-client-okhttp:3.5.2"
ktor-darwin = "io.ktor:ktor-client-darwin:3.5.2"
ktor-java = "io.ktor:ktor-client-java:3.5.2"
ktor-contentNegotiation = "io.ktor:ktor-client-content-negotiation:3.5.2"
ktor-kotlinxJson = "io.ktor:ktor-serialization-kotlinx-json:3.5.2"
ktor-mock = "io.ktor:ktor-client-mock:3.5.2"

coil-core = "io.coil-kt.coil3:coil-compose:3.5.0"
coil-ktor = "io.coil-kt.coil3:coil-network-ktor3:3.5.0"

navigation = "org.jetbrains.androidx.navigation:navigation-compose:2.9.2"

paths = "me.sujanpoudel.multiplatform.utils:multiplatform-paths:0.2.2"
